# Generated by Django 4.0.7 on 2022-11-10 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0007_evetype_description"),
        ("memberaudit", "0003_add_notify_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactercontact",
            name="eve_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveuniverse.eveentity",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="active_skill_level",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveuniverse.evetype",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="trained_skill_level",
            field=models.PositiveBigIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
