# Generated by Django 3.2.11 on 2022-02-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("memberaudit", "0008_add_compliance_groups"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComplianceGroup",
            new_name="ComplianceGroupDesignation",
        ),
    ]
