# Generated by Django 3.2.11 on 2022-02-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("memberaudit", "0008_compliancegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancegroup",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
